# Generated by Django 3.2.12 on 2022-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(max_length=255, unique=True, verbose_name='新闻id')),
                ('url', models.CharField(max_length=255, verbose_name='新闻原链接')),
                ('wapurl', models.CharField(max_length=255, verbose_name='新闻移动版原链接')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('intro', models.CharField(max_length=255, verbose_name='简介')),
                ('img', models.TextField(verbose_name='封面图')),
                ('images', models.TextField(verbose_name='图片列表')),
                ('keywords', models.CharField(max_length=255, verbose_name='关键词')),
                ('media_name', models.CharField(max_length=255, verbose_name='来源媒体')),
                ('subject', models.CharField(max_length=255, verbose_name='来源媒体')),
                ('text', models.TextField(verbose_name='新闻文本内容')),
                ('html', models.TextField(verbose_name='新闻结构内容')),
                ('intime', models.CharField(max_length=255, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻数据',
                'verbose_name_plural': '新闻数据',
                'db_table': 'news',
            },
        ),
    ]
