# Generated by Django 3.2.12 on 2022-07-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='点击率'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='新闻主题'),
        ),
    ]
